name: Secret Scan

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Gitleaks
        uses: gacts/gitleaks@c9a0338361dc45a01aa7ebaaa5330179f3c62873
        with:
          github-token: ${{ github.token }}
